return {
	{
		name = 'example',
		desc = 'example io application',
		version = "1.0",
		build = 'build01',
		author='cch',
		manufactor = 'OpenGate',
		path='master/example',
		type = 'app.io',
		depends = {},
		web = true,
	},
	{
		name = 'Modbus',
		desc = 'Modbus io application',
		build = 'build01',
		version = "1.0",
		author='cch',
		manufactor = 'OpenGate',
		type = 'app.io',
		depends = {},
		path='master/modbus',
		web = true,
	},
	{
		name = "S5500",
		desc = "旋思科技5500电表, Modbus协议",
		build = "build02",
		version = "1.1",
		author = 'dirk',
		manufactor = 'SymTech Inc.',
		type = 'app.io.config',
		depends = {'example'},
		path='master/s5500',
		web = true,
	},
	{
		name = "YeeLink",
		desc = "将数据采集转发到YeeLink数据平台",
		build = "build01",
		version = "0.1",
		author = 'dirk',
		manufactor = 'SymTech Inc.',
		type = 'app',
		depends = {},
		path='master/yeelink',
		web = true,
	},
}
